pipeline:
  identifier: Build_Krishna_Indium_springboot_k8s_yaml_1700563909695
  name: Build springboot-k8s-yaml
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Krishna-Indium/springboot-k8s-yaml
  stages:
    - stage:
        identifier: build
        name: springboot_app
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_hub
                    repo: docskrishna / harness_repo
                    tags:
                      - 21-11-2023
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
        description: ""
